# 01. Soccerdata Ingestion

**Stage:** Ingestion  
**Inputs:** `soccerdata` FBref, ClubElo, and Understat readers; EPL seasons from config  
**Outputs:** `data/raw/{season}/fixtures.parquet`, `data/raw/{season}/match_stats.parquet`, `data/processed/player_match_logs.parquet`

This notebook loads fixtures and team match statistics from FBref, then saves Understat player-match appearances. Understat omits players who did not appear; Stage 04 infers missing appearances only for established pre-fixture key starters.

In [1]:
# Load configuration and imports
%load_ext autoreload
%autoreload 2
from pathlib import Path
import sys

import pandas as pd

repo_root = Path.cwd()
while repo_root != repo_root.parent and not (repo_root / "src" / "config" / "loader.py").exists():
    repo_root = repo_root.parent
sys.path.insert(0, str(repo_root))

from src.config.loader import load_config
from src.ingestion.soccerdata_client import SoccerDataClient, SoccerDataConfig

config = load_config()
configured_seasons = config["data"]["seasons"]
league_id = config["data"]["default_league_id"]
ingestion_config = config["ingestion"]["soccerdata"]
print(f"Configured seasons: {configured_seasons}")
print(f"League ID: {league_id}")
fixtures_by_season = {}
match_stats_by_season = {}

[09/26/26 22:47:01] INFO     No custom team name replacements found. You can configure these in       ]8;id=15010402;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15010403;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_config.py#91\91]8;;\
                             /Users/mac/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=15010409;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15010410;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_config.py#189\189]8;;\
                             /Users/mac/soccerdata/config/league_dict.json.

Configured seasons: ['2024/2025', '2025/2026']
League ID: 47

In [2]:
# NBVAL_SKIP
client = SoccerDataClient(config=SoccerDataConfig(league=ingestion_config["league"]))
for season in configured_seasons:
    try:
        fixtures = client.fetch_fixtures(season=season, league_id=league_id)
        fixtures_by_season[season] = fixtures
        print(f"Fetched {len(fixtures)} fixtures for {season}")
    except Exception as exc:
        print(f"Error fetching fixtures for {season}: {exc}")
        fixtures_by_season[season] = None

                    INFO     Saving cached data to /Users/mac/soccerdata/data/FBref                  ]8;id=15010417;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010418;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

Fetched 380 fixtures for 2024/2025

[09/26/26 22:47:04] INFO     Saving cached data to /Users/mac/soccerdata/data/FBref                  ]8;id=15010423;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010424;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

Fetched 380 fixtures for 2025/2026

In [3]:
# NBVAL_SKIP
# Fetch team match statistics once per configured season.
for season in configured_seasons:
    fixtures = fixtures_by_season.get(season)
    try:
        if fixtures is not None and len(fixtures) > 0:
            match_stats_by_season[season] = client.fetch_all_match_stats(season=season)
            print(f"Fetched {len(match_stats_by_season[season])} team match-stat rows for {season}")
        else:
            match_stats_by_season[season] = None
    except Exception as exc:
        print(f"Error fetching match stats for {season}: {exc}")
        match_stats_by_season[season] = None

[09/26/26 22:47:05] INFO     Saving cached data to /Users/mac/soccerdata/data/FBref                  ]8;id=15010429;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010430;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

[09/26/26 22:47:09] INFO     Saving cached data to /Users/mac/soccerdata/data/Understat              ]8;id=15010435;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010436;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

[2026-09-26 22:47:09] INFO     TLSLibrary:_load_library:397 - Successfully loaded TLS library: /Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/tls_requests/bin/tls-client-darwin-arm64-1.13.1.dylib

                    INFO     Successfully loaded TLS library:                                      ]8;id=15010443;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/tls_requests/models/libraries.py\libraries.py]8;;\:]8;id=15010444;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/tls_requests/models/libraries.py#397\397]8;;\
                             /Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/pytho
                             n3.14/site-packages/tls_requests/bin/tls-client-darwin-arm64-1.13.1.d
                             ylib

Fetched 760 team match-stat rows for 2024/2025

[09/26/26 22:47:10] INFO     Saving cached data to /Users/mac/soccerdata/data/FBref                  ]8;id=15010449;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010450;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

[09/26/26 22:47:12] INFO     Saving cached data to /Users/mac/soccerdata/data/Understat              ]8;id=15010455;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010456;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

Fetched 760 team match-stat rows for 2025/2026

In [4]:
# Player match appearances from Understat
# Understat omits players who did not appear; missing key-starter rows are inferred in Stage 04.
player_minutes = None
print("Player appearance retrieval is handled by the Understat section below.")

Player appearance retrieval is handled by the Understat section below.

## Understat Player Match Appearances

Understat supplies player rows for actual appearances. Stage 04 compares these rows with each team's pre-fixture key-starter set to infer missing appearances without expanding all players against all fixtures.

In [5]:
# NBVAL_SKIP
understat_client = SoccerDataClient(
    config=SoccerDataConfig(
        league=ingestion_config["league"],
        seasons=tuple(config["data"]["seasons"]),
    )
)
processed_dir = repo_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

try:
    player_minutes = understat_client.fetch_player_match_stats()
    player_log_path = processed_dir / "player_match_logs.parquet"
    understat_client.save_parquet(player_minutes, str(player_log_path))
    print(f"Fetched and saved {len(player_minutes)} Understat player appearances")
    print(f"Saved player match logs to {player_log_path}")
except Exception as exc:
    print(f"Error fetching Understat player match appearances: {exc}")
    player_minutes = None

[09/26/26 22:47:13] INFO     Saving cached data to /Users/mac/soccerdata/data/Understat              ]8;id=15010461;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15010462;file:///Users/mac/Documents/Projects/SportsBettingPoisson+ML/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

Fetched and saved 23057 Understat player appearances
Saved player match logs to /Users/mac/Documents/Projects/SportsBettingPoisson+ML/data/processed/player_match_logs.parquet

In [6]:
# Save each configured season to its own raw-data directory
for season in configured_seasons:
    season_clean = season.replace("/", "-")
    output_dir = repo_root / "data" / "raw" / season_clean
    output_dir.mkdir(parents=True, exist_ok=True)

    fixtures = fixtures_by_season.get(season)
    match_stats = match_stats_by_season.get(season)
    if fixtures is not None and len(fixtures) > 0:
        fixtures.to_parquet(output_dir / "fixtures.parquet", index=False)
        print(f"Saved {len(fixtures)} fixtures for {season}")
    if match_stats is not None and len(match_stats) > 0:
        match_stats.to_parquet(output_dir / "match_stats.parquet", index=False)
        print(f"Saved {len(match_stats)} team match-stat rows for {season}")

Saved 380 fixtures for 2024/2025
Saved 760 team match-stat rows for 2024/2025
Saved 380 fixtures for 2025/2026
Saved 760 team match-stat rows for 2025/2026

In [7]:
for season in configured_seasons:
    fixtures = fixtures_by_season.get(season)
    match_stats = match_stats_by_season.get(season)
    if fixtures is not None and len(fixtures) > 0:
        print(f"Sample fixtures for {season}:")
        display(fixtures.head())
    if match_stats is not None and len(match_stats) > 0:
        print(f"Sample team match statistics for {season}:")
        display(match_stats.head())

Sample fixtures for 2024/2025:

,league,season,game,week,day,date,time,home_team,score,away_team,attendance,venue,referee,match_report,notes,fixture_id,home_goals,away_goals
0,ENG-Premier League,2425,2024-08-16 Manchester Utd-Fulham,1,Fri,2024-08-16,20:00,Manchester Utd,1–0,Fulham,73297,Old Trafford,Robert Jones,/en/matches/cc5b4244/Manchester-United-Fulham-...,<NA>,cc5b4244,1.0,0.0
1,ENG-Premier League,2425,2024-08-17 Arsenal-Wolves,1,Sat,2024-08-17,15:00,Arsenal,2–0,Wolves,60261,Emirates Stadium,Jarred Gillett,/en/matches/c0e3342a/Arsenal-Wolverhampton-Wan...,<NA>,c0e3342a,2.0,0.0
2,ENG-Premier League,2425,2024-08-17 Everton-Brighton,1,Sat,2024-08-17,15:00,Everton,0–3,Brighton,39217,Goodison Park,Simon Hooper,/en/matches/71618ace/Everton-Brighton-and-Hove...,<NA>,71618ace,0.0,3.0
3,ENG-Premier League,2425,2024-08-17 Ipswich Town-Liverpool,1,Sat,2024-08-17,12:30,Ipswich Town,0–2,Liverpool,30014,Portman Road Stadium,Tim Robinson,/en/matches/a1d0d529/Ipswich-Town-Liverpool-Au...,<NA>,a1d0d529,0.0,2.0
4,ENG-Premier League,2425,2024-08-17 Newcastle-Southampton,1,Sat,2024-08-17,15:00,Newcastle,1–0,Southampton,52196,St James' Park,Craig Pawson,/en/matches/34557647/Newcastle-United-Southamp...,<NA>,34557647,1.0,0.0

Sample team match statistics for 2024/2025:

,league,season,team,game,date,time,round,day,venue,result,...,Attendance,Captain,Formation,Opp Formation,Referee,match_report,Notes,Sh,SoT,xG
0,ENG-Premier League,2425,NaN,2024-08-16 Manchester Utd-nan,2024-08-16,20:00:00,Matchweek 1,Fri,Away,L,...,73297,Bernd Leno,4-2-3-1,4-2-3-1,Robert Jones,/en/matches/cc5b4244/Manchester-United-Fulham-...,<NA>,10,2,NaN
1,ENG-Premier League,2425,NaN,2024-08-16 nan-Fulham,2024-08-16,20:00:00,Matchweek 1,Fri,Home,W,...,73297,Bruno Fernandes,4-2-3-1,4-2-3-1,Robert Jones,/en/matches/cc5b4244/Manchester-United-Fulham-...,<NA>,14,5,NaN
2,ENG-Premier League,2425,NaN,2024-08-17 Arsenal-nan,2024-08-17,15:00:00,Matchweek 1,Sat,Away,L,...,60261,Mario Lemina,4-2-3-1,4-3-3,Jarred Gillett,/en/matches/c0e3342a/Arsenal-Wolverhampton-Wan...,<NA>,9,3,NaN
3,ENG-Premier League,2425,NaN,2024-08-17 Everton-nan,2024-08-17,15:00:00,Matchweek 1,Sat,Away,W,...,39217,Lewis Dunk,4-2-3-1,4-2-3-1,Simon Hooper,/en/matches/71618ace/Everton-Brighton-and-Hove...,<NA>,10,5,NaN
4,ENG-Premier League,2425,NaN,2024-08-17 Ipswich Town-nan,2024-08-17,12:30:00,Matchweek 1,Sat,Away,W,...,30014,Virgil van Dijk,4-2-3-1,4-2-3-1,Tim Robinson,/en/matches/a1d0d529/Ipswich-Town-Liverpool-Au...,<NA>,18,5,NaN

Sample fixtures for 2025/2026:

,league,season,game,week,day,date,time,home_team,score,away_team,attendance,venue,referee,match_report,notes,fixture_id,home_goals,away_goals
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,1,Fri,2025-08-15,20:00,Liverpool,4–2,Bournemouth,60315,Anfield,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,<NA>,a071faa8,4.0,2.0
1,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle,1,Sat,2025-08-16,12:30,Aston Villa,0–0,Newcastle,42526,Villa Park,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...,<NA>,bbdf4739,0.0,0.0
2,ENG-Premier League,2526,2025-08-16 Brighton-Fulham,1,Sat,2025-08-16,15:00,Brighton,1–1,Fulham,31478,The American Express Stadium,Samuel Barrott,/en/matches/57c49bae/Brighton-and-Hove-Albion-...,<NA>,57c49bae,1.0,1.0
3,ENG-Premier League,2526,2025-08-16 Sunderland-West Ham,1,Sat,2025-08-16,15:00,Sunderland,3–0,West Ham,46233,Stadium of Light,Robert Jones,/en/matches/e1058522/Sunderland-West-Ham-Unite...,<NA>,e1058522,3.0,0.0
4,ENG-Premier League,2526,2025-08-16 Tottenham-Burnley,1,Sat,2025-08-16,15:00,Tottenham,3–0,Burnley,61077,Tottenham Hotspur Stadium,Michael Oliver,/en/matches/d41bb8b3/Tottenham-Hotspur-Burnley...,<NA>,d41bb8b3,3.0,0.0

Sample team match statistics for 2025/2026:

,league,season,team,game,date,time,round,day,venue,result,...,Attendance,Captain,Formation,Opp Formation,Referee,match_report,Notes,Sh,SoT,xG
0,ENG-Premier League,2526,NaN,2025-08-15 Liverpool-nan,2025-08-15,20:00:00,Matchweek 1,Fri,Away,L,...,60315,Adam Smith,4-1-4-1,4-2-3-1,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,<NA>,10,3,NaN
1,ENG-Premier League,2526,NaN,2025-08-15 nan-Bournemouth,2025-08-15,20:00:00,Matchweek 1,Fri,Home,W,...,60315,Virgil van Dijk,4-2-3-1,4-1-4-1,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,<NA>,19,10,NaN
2,ENG-Premier League,2526,NaN,2025-08-16 Aston Villa-nan,2025-08-16,12:30:00,Matchweek 1,Sat,Away,D,...,42526,Bruno Guimarães,4-3-3,4-2-3-1,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...,<NA>,16,3,NaN
3,ENG-Premier League,2526,NaN,2025-08-16 Brighton-nan,2025-08-16,15:00:00,Matchweek 1,Sat,Away,D,...,31478,Bernd Leno,4-2-3-1,4-2-3-1,Samuel Barrott,/en/matches/57c49bae/Brighton-and-Hove-Albion-...,<NA>,7,2,NaN
4,ENG-Premier League,2526,NaN,2025-08-16 Sunderland-nan,2025-08-16,15:00:00,Matchweek 1,Sat,Away,L,...,46233,Jarrod Bowen,3-4-1-2,4-3-3,Robert Jones,/en/matches/e1058522/Sunderland-West-Ham-Unite...,<NA>,12,4,NaN

In [8]:
print("=== Data Validation ===")
for season in configured_seasons:
    fixtures = fixtures_by_season.get(season)
    match_stats = match_stats_by_season.get(season)
    if fixtures is not None and len(fixtures) > 0:
        required_columns = ["fixture_id", "home_team", "away_team", "date"]
        missing_columns = [column for column in required_columns if column not in fixtures.columns]
        print(f"{season} fixtures: {len(fixtures)} rows")
        print(f"{season} missing required columns: {missing_columns}")
    if match_stats is not None and len(match_stats) > 0:
        print(f"{season} team match stats: {len(match_stats)} rows")
print("=== Ingestion Complete ===")

=== Data Validation ===
2024/2025 fixtures: 380 rows
2024/2025 missing required columns: []
2024/2025 team match stats: 760 rows
2025/2026 fixtures: 380 rows
2025/2026 missing required columns: []
2025/2026 team match stats: 760 rows
=== Ingestion Complete ===